name: Mirror to Gitee

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: 下载源文件
      run: |
        wget https://github.com/CMSZ002/cmsz002.github.io/archive/refs/heads/main.zip
        unzip main.zip
        rm main.zip
        git clone https://gitee.com/CMSZ001/cmsz002.github.io.git
        ls
