name: Mirror to Gitee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 下载源文件
      run: |
        wget https://github.com/CMSZ002/cmsz002.github.io/archive/refs/heads/main.zip
        unzip main.zip
        ls
