name: 镜像至gitee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 配置git仓库
      run: |
        wget https://github.com/CMSZ002/cmsz002.github.io/archive/refs/heads/main.zip
        unzip main.zip
        git clone https://gitee.com/CMSZ001/cmsz002.github.io.git
        cd cmsz002.github.io
        rm -r docs LICENSE
        cd /home/runner/work/cmsz002.github.io/cmsz002.github.io
        cd cmsz002.github.io-main
        cp -r . /home/runner/work/cmsz002.github.io/cmsz002.github.io/cmsz002.github.io/
        cd /home/runner/work/cmsz002.github.io/cmsz002.github.io/cmsz002.github.io

    - name: 推送至gitee
      run: |
        cd cmsz002.github.io

      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/Hargeek  # 源端账户名(github)
        dst: gitee/ssgeek  # 目的端账户名(gitee)
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "python-nianbao-struct"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作