name: 镜像至gitee

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: 配置git仓库
      run: |
        wget https://github.com/CMSZ002/cmsz002.github.io/archive/refs/heads/main.zip
        unzip main.zip
        git clone https://gitee.com/CMSZ001/cmsz002.github.io.git
        cd cmsz002.github.io
        rm -r docs LICENSE
        cd /home/runner/work/cmsz002.github.io/cmsz002.github.io
        cd cmsz002.github.io-main
        cp -r . /home/runner/work/cmsz002.github.io/cmsz002.github.io/cmsz002.github.io/
        cd /home/runner/work/cmsz002.github.io/cmsz002.github.io/cmsz002.github.io

    - name: 推送至gitee
      run: |
        git config --global user.name "CMSZ001"
        git config --global user.email "2706210065@qq.com"
        git remote set-url --push origin https://username:${{ secrets.GITEE_TOKEN }}@gitee.com/CMSZ001/cmsz002.github.io.git
        git push origin HEAD:main --force
        
