name: 图片压缩
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 使用checkout
      uses: actions/checkout@v4

    - name: 使用 Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: 安装squoosh-cli
      run: npm install -g @squoosh/cli

    - name: 开始压缩图片
      run: |
        cd docs
        ls
        #cd _images
        #squoosh-cli --mozjpeg auto ./
        
